src/protected/models/Files.php
<?php

class Files extends EMongoDocument
{
	public $name;
	/* @string file name */
	public $category;
	/* @string document category */
	public $user;
	/* @string user uploaded document */

	public $status;
	/* @int document status */
	public $title;
	/* @string material description */
	public $authors;
	/* @string authors of document */
	public $courses;
	/* @string courses which includes document */
	public $description;
	/* @text material description in text */
	public $description_mkd;
	/* @text material description in markdown */
	public $year;
	/* @int material version */
	public $time_approved;
	/* @mongodate approved material */
	public $time_updated;
	/* @mongodate updated material */

	public $rating;
	/* @float calculating every hour */

	public $votes;

	public $comments;

	public $parent;

	public $coursesData;

	public $sphinx_id;

	/* CONSTANTS */
	const
		TYPE_LECTURES = 'lectures',
		TYPE_BOOKS = 'books',
		TYPE_TEXTBOOKS = 'textbooks',
		TYPE_MATERIALS = 'materials',
		STATUS_APPROVED = 1,
		STATUS_NOT_APPROVED = 2,
		STATUS_PENDING = 3,
		STATUS_CHILD_FILE = 4;

	// This has to be defined in every model, this is same as with standard Yii ActiveRecord
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function collectionName()
	{
		return 'storage.files';
	}

	public function versioned()
	{
		return true;
	}

	public function versionField()
	{
		return '_v'; // This is actually the default value in EMongoDocument
	}

	public function rules()
	{
		return array(
			array('title, year,description_mkd, courses, description, category, authors', 'required', 'on' => 'update'),
			array('authors', 'length', 'max' => 140),
			array('category', 'in', 'range' => array_keys(CListDataHelper::getListData('category'))),
			array('status', 'in', 'range' => array_keys(CListDataHelper::getListData('status'))),
			array('year', 'numerical', 'min' => '1890', 'max' => date('Y'), 'integerOnly' => true),
			array('name, user', 'safe', 'on' => 'insert'),
			array('time_created, time_updated', 'safe'),
			array('description', 'filter', 'filter' => array($obj = new CHtmlPurifier(), 'purify'))
		);
	}

	public function attributeLabels()
	{
		return [
			'description_mkd' => Yii::t('form', 'Description'),
			'authors' => Yii::t('form', 'Authors'),
			'category' => Yii::t('form', 'Category'),
			'title' => Yii::t('form', 'Title'),
			'year' => Yii::t('form', 'Year')
		];
	}

	public function beforeSave()
	{
		if ($this->scenario == 'update') {
			$courseList = explode(',', $this->courses);
			foreach ($courseList as $course) {
				//TODO: add check on error
				$info = CJSON::decode(file_get_contents(sprintf('http://api.usic.at/api/v1/courses/autocomplete?q=%s&limit=100&match=1', $course)));
				foreach ($info as $value) {
					$this->coursesData[] = $value;
				}
			}
		}
		if ($this->getScenario() == 'update' && $this->status != self::STATUS_APPROVED) {
			$preview = new PreviewGenerator();
			$params = param('preview');
			$preview->previewPath = Yii::getPathOfAlias($params['path']) . DIRECTORY_SEPARATOR;
			foreach ($params['dimensions'] as $dim) {
				$preview->width = $dim['width'];
				$preview->height = $dim['height'];
				$preview->prefix = $dim['prefix'];
				$preview->generateById($this->_id);
			}
			$this->status = self::STATUS_PENDING;
		}
		$this->time_updated = new MongoDate();
		return parent::beforeSave();
	}

	public function beforeValidate()
	{
		if (!empty($this->description_mkd)) {
			$md = new CMarkdown;
			$pu = new CHtmlPurifier;
			$this->description_mkd = $pu->purify($this->description_mkd);
			$this->description = $md->transform($this->description_mkd);
		}
		return parent::beforeValidate();
	}

	public function file() // file storage
	{
		return FileStorage::model()->findOne(array('_id' => new MongoId($this->_id)));
	}

	public function recently($limit = 10)
	{
		$this->mergeDbCriteria([
			'order' => 'uploadDate DESC',
			'limit' => $limit,
		]);
		return $this;
	}

	public function approved()
	{
		$this->mergeDbCriteria([
			'condition' => array('status' => Files::STATUS_APPROVED),
		]);
		return $this;
	}

	public function notApproved()
	{
		$this->mergeDbCriteria([
			'condition' => ['status' => Files::STATUS_NOT_APPROVED],
			'sort'      => ['time_updated' => -1]
		]);
		return $this;
	}

	public function pending()
	{
		$this->mergeDbCriteria([
			'condition' => array('status' => Files::STATUS_PENDING),
		]);
		return $this;
	}

	public function approve()
	{
		return $this->setStatus(self::STATUS_APPROVED);
	}

	public function deny()
	{
		return $this->setStatus(self::STATUS_NOT_APPROVED);
	}

	public function setChild()
	{
		return $this->setStatus(self::STATUS_CHILD_FILE);
	}

	private function setStatus($status)
	{
		$this->status = $status;
		return $this->save(false);
	}

	/**
	 * Return tags from all approved files
	 * @return array
	 */
	static public function getTags()
	{
		$query = array(
			"tags"   => array('$ne' => null),
			"status" => Files::STATUS_APPROVED
		);
		$tags = db()
			->command(array(
					"distinct" => "files",
					"key"      => "tags",
					"query"    => $query)
			);
		$tags = $tags['values'];
		return is_null($tags) ? array() : $tags;
	}

	static public function humanSize($b)
	{
		return round($b / 1024 / 1024, 2) . ' Mb';
	}

	static public function getPreview($id, $size = 's')
	{
		$path = Yii::getPathOfAlias(param('preview')['path']) . DIRECTORY_SEPARATOR . $size . $id . '.jpg';
		if (file_exists($path)) {
			return str_replace(Yii::getPathOfAlias('webroot'), '', $path);
		}
		return 'http://placehold.it/120x160';
	}
}

src/protected/controllers/FilesController.php
<?php

class FilesController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete,confirm,vote', // we only allow deletion via POST request
		);
	}

	private $_accessExpresions = [
		'toModerate' => 'Yii::app()->user->inGroup("nimda")',
		'toVoteDown' => 'Files::model()->findByAttributes(array("user" => Yii::app()->user->name, "status" => Files::STATUS_APPROVED)) != null', //TODO More efficient
	];

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 *
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array(
				'allow',
				'actions' => array('index', 'view', 'popular', 'search', 'course', 'courses', 'quickSearch'),
				'users'   => array('*'),
			),
			array(
				'allow',
				'actions' => array('new', 'upload', 'recommended', 'my', 'voteUp', 'download'),
				'users'   => array('@'),
			),
			array(
				'allow',
				'actions' => array('update', 'delete'),
				'users'   => array('@')
			),
			array(
				'allow',
				'actions'    => array('voteDown'),
				'users'      => array('@'),
				'expression' => $this->_accessExpresions['toVoteDown']
			),
			array(
				'allow',
				'actions'    => array('moderateList', 'moderate', 'approve', 'approveChild', 'deny'),
				'users'      => array('@'),
				'expression' => $this->_accessExpresions['toModerate']
			),
			array(
				'deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * @param string $query
	 */
	public function actionIndex($query = '')
	{
		$this->filter = true;
		$dataProvider = new EMongoDataProvider(Files::model()->approved(), array(
			'pagination' => array(
				'pageSize' => 5
			)
		));
		$this->render(
			'index', array(
				'data' => $dataProvider
			)
		);
	}

	/**
	 * Renders form form uploading
	 * or display dialog
	 */
	public function actionNew()
	{
		$this->render('_upload_form');
	}

	/** MODERATION */


	public function actionModerateList()
	{
		$dataProvider = new EMongoDataProvider(Files::model()->notApproved());
		$this->render(
			'moderateList', array(
				'data' => $dataProvider
			)
		);
	}

	/**
	 * Mark file as approved.
	 * Only files with full
	 * info can be approved
	 */
	public function actionApprove($id)
	{
		/* action can be preformed only by moderators */
		$file = $this->loadModel($id);
		if (!$file->approve()) {
			throw new CHttpException(418, "Model can not be saved");
		}
	}

	public function actionDeny($id)
	{
		/* action can be preformed only by moderators */
		//TODO Send message to user
		$file = $this->loadModel($id);
		if (!$file->deny()) {
			throw new CHttpException(418, "Model can not be saved");
		}
	}

	public function actionApproveChild($id)
	{
		/* action can be preformed only by moderators */
		//TODO Send message to user
		$file = $this->loadModel($id);
		if (!$file->setChild()) {
			throw new CHttpException(418, "Model can not be saved");
		}
	}

	public function actionModerate($id)
	{
		$file = $this->loadModel($id);

		if (isset($_POST['Files'])) {
			$file->setScenario('update');
			$file->attributes = $_POST['Files'];
			if ($file->validate() && $file->save()) {
				echo CJSON::encode(['success' => Yii::t('app', 'File information updated')]);
			}
		}

		$this->render(
			'moderate', array(
				'model' => $file
			)
		);
	}

	/* MODERATION END */
	/**
	 * Displays found file's data
	 *
	 * @param $q
	 *
	 */
	public function actionSearch($q)
	{
		if (empty($q) || strlen($q) < 3) {
			echo CJSON::encode(array('error' => Yii::t('app', 'The query length can not be less then 3 chars')));
			Yii::app()->end();
		}
		if (!extension_loaded("sphinx")) {
			echo CJSON::encode(
				array(
					'class_error' => Yii::t('app', 'No sphinx module is available.It must be installed and enable to use search.')
				)
			);
			Yii::app()->end();
		}
		$criteria = new ESphinxSearchCriteria(array(
			'sortMode'   => ESphinxSort::RELEVANCE,
			'matchMode'  => ESphinxMatch::PHRASE,
			'maxMatches' => 50,
			'limit'      => 10
		));

		$query = new ESphinxQuery($this->escapeString($q), 'books', $criteria); // search in all fields
		$sq_result = Yii::app()->sphinx->executeQuery($query);

		if ($sq_result->count() == 0) {
			echo CJSON::encode(array('no_results_found' => Yii::t('app', 'Try to use custom search')));
			Yii::app()->end();
		}

		for ($i = 0; $i < $sq_result->count(); $i++) {
			if ($sq_result->offsetExists($i)) {
				$item = $sq_result->offsetGet($i);
				$ids[] = new MongoInt64($item->id);
				$weights[$item->id] = $item->weight;
			}
		}
		//use code below to get data from database
		$data = db()->storage->files->find(
			array('sphinx_id' => array('$in' => $ids)),
			array(
				'title'     => 1,
				'authors'   => 1,
				'sphinx_id' => 1
			)
		)
			->limit(10);
		if (iterator_count($data) == 0) {
			echo CJSON::encode(array('no_data_to_return' => Yii::t('app', 'Try to use search in few minutes')));
			Yii::app()->end();
		}
		//this must be simplest
		foreach ($weights as $id => $weight) {
			foreach ($data as $doc_id => $document) {
				if ($id == $document['sphinx_id']) {
					$document['id'] = strval($document['_id']);
					unset($document['_id']);
					unset($document['sphinx_id']);
					$result[] = $document;
				}
			}
		}
		echo CJSON::encode($result);
	}

	public function actionRecommended()
	{
		$this->render('index', ['data' => new EMongoDataProvider(Files::model()->recently()->approved(), [
			'pagination' => false
		])]);
	}

	/**
	 * @return latest files
	 */
	public function actionHot()
	{
		$this->render('index', [
				'data' => new EMongoDataProvider(Files::model()->recently()->approved(), [
						'pagination' => false
					]
				)
			]
		);
	}

	/**
	 * Renders user's file list
	 */
	public function actionMy()
	{
		$c = new EMongoCriteria;
		$c->addCondition('user', Yii::app()->user->login);
		$c->setSort(array('uploadDate' => -1));
		$dataProvider = new EMongoDataProvider('Files', array(
			'criteria' => $c,
		));
		$this->render(
			'my', array(
				'data' => $dataProvider
			)
		);
	}

	private function vote($type)
	{
		switch ($type) {
			case 'up':
				$voteNumber = 1;
				$votePlus = 2;
				break;
			case 'down':
				$voteNumber = -1;
				$votePlus = -2;
				break;
		}
		$file = Files::model()->findByPk(new MongoId(CHttpRequest::getParam('id')));
		if ($file != null) {
			$user = Yii::app()->user->name;
			if (isset($file->votes)) {
				foreach ($file->votes as $vote) {
					if ($vote->user == $user && $vote->vote != -($voteNumber)) {
						echo CJSON::encode(array('error' => Yii::t('app', 'You can`t vote anymore')));
						Yii::app()->end();
					} elseif ($vote->user == $user) {
						$voteNumber = $votePlus;
					}
				}
			}
			$file->votes[] = new FileVote;
			end($file->votes)->user = $user;
			end($file->votes)->vote = $voteNumber;
			end($file->votes)->created = new MongoDate();
			$file->save();
			echo CJSON::encode(array('success' => Yii::t('app', 'Thank you for voting')));
		} else {
			echo CJSON::encode(array('error' => Yii::t('app', 'No such file')));
		}
		Yii::app()->end();
	}

	public function actionVoteUp()
	{
		$this->vote('up');
	}

	public function actionVoteDown()
	{
		$this->vote('down');
	}

	/**
	 * Out file stream to browser,
	 * send headers for saving file,
	 * increment download counter
	 *
	 * @param $id
	 *
	 * @throws CHttpException
	 */
	public function actionDownload($id)
	{
		$f = FileStorage::model()->findByPk(new MongoId($id));
		if (is_null($f)) {
			throw new CHttpException(404, Yii::t('app', 'Requested file does not exists.'));
		}
		if ($f->getFile()->file['status'] == Files::STATUS_NOT_APPROVED) {
			throw new CHttpException(403, Yii::t('app', 'This file has not been approved yet.'));
		}
		$stream = $f->getFile()->getResource();
		header('Content-Description: File Transfer');
		header('Content-type: ' . $f->getFile()->file['mime']);
		header('Content-Disposition: attachment; filename=' . ($f->getFile()->file['name']));
		header('Content-Transfer-Encoding: binary');
		header('Pragma: public');
		header('Content-Length: ' . $f->getFile()->getSize());
		while (!feof($stream)) {
			echo fread($stream, 8192);
		}
		Files::model()->updateByPk($f->_id, array('$inc' => array("downloads" => 1)));
	}

	/**
	 * Renders single document
	 *
	 * @param $id
	 *
	 * @throws 403 error if status not_approved
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);
		if ($model->status == Files::STATUS_NOT_APPROVED) {
			throw new CHttpException('403', Yii::t('app', 'Access denied to not approved materials'));
		}
		$this->render('view', array('model' => $model));
	}

	/**
	 * Delete single document
	 *
	 * @param $id
	 *
	 * @throws CHttpException
	 */
	public function actionDelete($id)
	{
		$model = $this->loadModel($id);
		if (!$this->_isOwner($model) || $model->status == Files::STATUS_APPROVED) {
			throw new CHttpException(403, Yii::t('app', 'You can not delete this material'));
		}
		try{
			$model->delete();
			echo CJSON::encode(['status' => 'success']);
		}
		catch(Exception $e){
			echo CJSON::encode(['status' => 'error','message'=>$e->getMessage()]);
		}
	}

	/**
	 * Handle post request,
	 * output status in json format
	 */
	public function actionUpload()
	{
		header('Content-Type: application/json');
		if ($file = CUploadedFile::getInstanceByName('file')) {
			$model = new FileStorage();
			$model->file = $file;
			if (isset($_POST['parent'])) {
				$model->parent = $_POST['parent'];
				$model->setScenario('childFile');
			} else {
				$model->setScenario('checkFile');
			}
			if ($model->validate()) {
				unset($model->file);
				$model->setScenario('insert');
				$file->saveAs($file->getTempName());
				$model->name = $file->getName();
				$model->mime = $file->getType();
				$model->setFile($file->getTempName());
				$model->addFileToQueue();
			} else {

src/protected/views/files/_form.php
<div class="form">
	<?php $form = $this->beginWidget('CActiveForm', array(
		'id'                   => 'file-form',
		'enableAjaxValidation' => false,
		'htmlOptions'          => array(
			'class' => 'pure-form pure-form-aligned'
		)
	)); ?>

	<?php echo $form->errorSummary($model); ?>
	<fieldset>
		<legend class="edit">Редагування матеріалу <b><?php echo CHtml::encode($model->name); ?></b></legend>
		<div class="inline-block">
		<div class="pure-control-group form-group">
			<?php echo $form->labelEx($model, 'title'); ?>
			<?php echo $form->textField($model, 'title', array('class' => 'form-control', 'size' => 60, 'maxlength' => 255, 'required' => 'required')); ?>
		</div>

		<div class="pure-control-group form-group">
			<?php echo $form->labelEx($model, 'year'); ?>
			<?php echo $form->textField($model, 'year', array('class' => 'form-control', 'required' => 'required', 'type' => 'year')); ?>
		</div>

		<div class="pure-control-group form-group">
			<?php echo $form->labelEx($model, 'authors'); ?>
			<?php echo $form->textField($model, 'authors', array('class' => 'form-control', 'required' => 'required')); ?>
		</div>

		<div class="pure-control-group form-group">
			<?php echo $form->labelEx($model, 'courses'); ?>
			<?php echo $form->textField($model, 'courses');
			$this->widget('application.lib.select2.ESelect2', array(
				'name'        => 'Files_courses',
				'htmlOptions' => array(
					'class'   => 'pure-input-1'
				),
				'selector'    => '#Files_courses',
				'options'     => array(
					'placeholder'        => Yii::t('app', 'Select a subject'),
					'allowClear'         => false,
					'multiple'           => true,
					'width'              => '400px',
					'minimumInputLength' => 1,
					'ajax'               => array(
						'url'      => 'http://api.usic.at/api/v1/courses/autocomplete?limit=100',
						'dataType' => 'jsonp',
						'data'     => 'js: function(term,page) {
    						return {
    							q: term
    						};
    					}',
						'results'  => 'js: function(data,page){
							return {results: data};
						}',
					),
					'formatResult'       => 'js: function(value){
    					var markup = "<table class=\"value-result\"><tr><td>";
    					markup += "<div>"+value.course+"</div>";
    					markup += "<div>"+"Рік - "+value.year+"</div>";
    					markup += "<div>"+value.level+"</div>";
    					markup += "</td></tr></table>";
    					return markup;
    				}',
					'formatSelection'    => 'js: function(value){
    					return value.course;
    				}',
					'initSelection'      => 'js:function(element, callback) {
                        var data = [];
                        $(element.val().split(",")).each(function (k,v) {
                            data.push({id: v, course: v});

                        });
                        callback(data);
                    }'
				),
			));
			?>
		</div>

		<div class="pure-control-group form-group">
			<?php echo $form->labelEx($model, 'category', array('id' => 'checkbox-inline')); ?>
			<?php echo $form->radioButtonList($model, 'category', CListDataHelper::getListData('category'), array(
					'separator'    => "",
					'labelOptions' => array('style' => 'display:inline'),
				 	'required'       => 'required'
				)
			); ?>
		</div>

		<div class="pure-control-group form-group">
			<?php echo $form->labelEx($model, 'description_mkd', array('class' => 'comment-label')); ?>
			<?php echo $form->textArea($model, 'description_mkd', array('class' => 'form-control', 'rows' => '6' , 'required' => 'required')); ?>
		</div>

		<div class="pure-controls save">
			<?php echo CHtml::submitButton(Yii::t('app', 'Save'), array('class' => 'btn btn-default')); ?>
		</div>
		</div>
	</fieldset>
	<?php $this->endWidget(); ?>

</div><!-- form -->

src/protected/views/files/_upload_form.php
<?php
/* @var $this SiteController */
Yii::app()->getClientScript()->registerCssFile(Yii::app()->baseUrl . '/css/dropzone.css');
Yii::app()->getClientScript()->registerScriptFile(Yii::app()->baseUrl . '/js/dropzone.min.js',CClientScript::POS_END);
$this->pageTitle = 'Завантаження файлу - ' . Yii::app()->name;
?>
<?php if (Yii::app()->user->hasFlash('error')): ?>
	<div class="info">
		<?php echo Yii::app()->user->getFlash('error'); ?>
	</div>
<?php endif; ?>

<section>
	<div id="dropzone">
		<form action="<?php echo $this->createUrl('files/upload'); ?>" class="dropzone dz-clickable" id="my-dropzone">
			<div class="dz-default dz-message">
				<span>(або клікніть)</span>
			</div>
		</form>
	</div>
</section>

src/protected/views/files/_view.php
<book class="pure-u-xl-1-3 pure-u-md-1-2 pure-u-sm-1-2 pure-u-1">
	<span
		class="title"><h4><?php echo CHtml::link(CHtml::encode($data->title), array('/files/view', 'id' => strval($data->_id))); ?>  </h4></span>

	<div class="pure-g">
		<div class="pure-u-1-2">
			<img src="<?php echo Files::getPreview(strval($data->_id)); ?>" class="pure-img">
		</div>
		<div class="pure-u-1-2">
			<ul>
				<li class="category <?php echo $data->category; ?>"><?php echo CListDataHelper::getLabel('category', $data->category); ?></li>
				<li class="year"><?php echo $data->year; ?> рік</li>
				<li title="<?php echo $data->authors; ?>"><?php echo $data->authors; ?></li>
				<li><?php echo mb_strcut($data->description, 0, 140, 'utf-8'); ?></li>
			</ul>
		</div>
	</div>
</book>

src/protected/views/files/courses.php
<?php if(count($data)<1):?>
	<?php echo Yii::t('app','Here are no any courses yet');?>
<?php else:?>
<?php
echo CHtml::openTag('ul');
foreach ($data as $course) {
	echo CHtml::openTag('li') . CHtml::link($course, array('files/course', 'id' => $course)) . CHtml::closeTag('li');
}
echo CHtml::closeTag('ul');	?>
<?php endif;?>

src/protected/views/files/index.php
<?php
$this->widget('zii.widgets.CListView', array(
	'id'            => 'file-list',
	'dataProvider'  => $data,
	'itemView'      => '_view',
	'enableSorting' => false,
	'cssFile'       => false,
	'template'      => '{pager}{items}{pager}',
	'itemsCssClass' => 'pure-g',
	'pager'         => array(
		'class' => 'CustomLinkPager'
	),
));

src/protected/views/files/moderate.php
<?php

$this->renderPartial("_form", ['model' => $model]);

if(isset($model->parent))
	echo CHtml::link("Дочірній файл", $this->createUrl('files/view', ['id' => $model->_id]));

echo CHtml::ajaxButton("Підтвердити",
	$model->parent ? $this->createUrl('files/approveChild', ['id' => $model->_id]) : $this->createUrl('files/approve', ['id' => $model->_id]),
	[
		'type'=>'GET',
		'dataType'=>'json',
		'success'=> 'function(){ alert("Підтверджено");s}',
		'error'=>'function(data){ alert(data.error);}'
	]);

echo CHtml::ajaxButton("Відхилити",
	$this->createUrl('files/deny', ['id' => $model->_id]),
	[
		'type'=>'GET',
		'dataType'=>'json',
		'success'=> 'function(){ alert("Відхилено");s}',
		'error'=>'function(data){ alert(data.error);}'
	]);

src/protected/views/files/moderateList.php
<h1><?php echo Yii::t('app', 'Files to moderate'); ?></h1>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'           => 'files-grid',
	'pager'        => array(
		'class' => 'CustomLinkPager'
	),
	'dataProvider' => $data,
	'columns'      => array(
		array(
			'name'  => 'time_updated',
			'value' => 'date("h:i:s d-M-Y", $data->time_updated)'
		),
		array(
			'name'  => 'name',
			'value' => 'strlen($data->title)>10 ? $data->title:$data->name'
		),
		array(
			'name'  => 'fileSize',
			'value' => 'Files::humanSize($data->length)'
		),
		array(
			'name'  => 'category',
			'value' => 'CListDataHelper::getLabel("category",$data->category)'
		),
		array(
			'class'   => 'CButtonColumn',
			'buttons' => array(
				'moderate'   => array(
					'label' => 'Moderate',
					'url' => 'Yii::app()->createUrl("files/moderate", array("id" => $data->_id))',
				),
				'delete'
			),
			'template' => '{moderate}{delete}'
		)
	)
)); ?>

src/protected/views/files/my.php
<h1><?php echo Yii::t('app', 'My files'); ?></h1>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'           => 'files-grid',
	'pager'        => array(
		'class' => 'CustomLinkPager'
	),
	'itemsCssClass' => 'table table-hover',
	'rowCssClassExpression' => '
		($data->status == 1) ? "success" : (($data->status == 2) ? "danger" : (($data->status == 3) ? "warning" : "none"))
	',
	'dataProvider' => $data,
	'columns'      => array(
		array(
			'name'  => 'name',
			'value' => 'strlen($data->title)>10 ? $data->title:$data->name'),
		array(
			'name'  => 'fileSize',
			'value' => 'Files::humanSize($data->length)'
		),
		array(
			'name'  => 'status',
			'value' => 'CListDataHelper::getLabel("status",$data->status)'
		),
		array(
			'name'  => 'category',
			'value' => 'CListDataHelper::getLabel("category",$data->category)'
		),
		array(
			'class'   => 'CButtonColumn',
			'buttons' => array(
				'view'   => array(
					'visible' => '$data->status!=Files::STATUS_NOT_APPROVED',
					'options'=>array('title'=>'Переглянути')
				),
				'update' => array(
					'visible' => '$data->status!=Files::STATUS_APPROVED',
					'options'=>array('title'=>'Редагувати')
				),
				'delete' => array(
					'visible' => '$data->status!=Files::STATUS_APPROVED',
					'options'=>array('title'=>'Видалити')
				)
			)
		)
	)
)); ?>

src/protected/views/files/view.php
<article>
	<h1><?php echo CHtml::encode($model->title); ?></h1>
	<img src="<?php echo Files::getPreview(strval($model->_id), 'm'); ?>" class="pure-img left"/>
	<ul>
		<li>Year: <?php echo $model->year; ?></li>
		<li>Author: <?php echo $model->authors; ?></li>
		<li>Description:<?php echo $model->description; ?></li>
	</ul>
	<?php $this->widget('CStarRating', array(
		'name'      => 'rating',
		'value'     => '4',
		'minRating' => 1,
		'maxRating' => 10,
		'starCount' => 10,
	));?>
	<?php echo CHtml::link(Yii::t('app', 'Download'), array('/files/download', 'id' => $model->_id, 'name' => $model->name), array('target' => '_blank')); ?>

	<div>
		<?php $this->renderPartial('//comments/_comments',array(
			'comments'=>$model->comments,
			'file'=>$model->_id
		)); ?>
	</div>
</article>