src/protected/controllers/FilesController.php
<?php

class FilesController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete,confirm,vote', // we only allow deletion via POST request
		);
	}

	private $_accessExpresions = [
		'toModerate' => 'Yii::app()->user->inGroup("nimda")',
		'toVoteDown' => 'Files::model()->findByAttributes(array("user" => Yii::app()->user->name, "status" => Files::STATUS_APPROVED)) != null', //TODO More efficient
	];

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 *
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array(
				'allow',
				'actions' => array('index', 'view', 'popular', 'search', 'course', 'courses', 'quickSearch'),
				'users'   => array('*'),
			),
			array(
				'allow',
				'actions' => array('new', 'upload', 'recommended', 'my', 'voteUp', 'download'),
				'users'   => array('@'),
			),
			array(
				'allow',
				'actions' => array('update', 'delete'),
				'users'   => array('@')
			),
			array(
				'allow',
				'actions'    => array('voteDown'),
				'users'      => array('@'),
				'expression' => $this->_accessExpresions['toVoteDown']
			),
			array(
				'allow',
				'actions'    => array('moderateList', 'moderate', 'approve', 'approveChild', 'deny'),
				'users'      => array('@'),
				'expression' => $this->_accessExpresions['toModerate']
			),
			array(
				'deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * @param string $query
	 */
	public function actionIndex($query = '')
	{
		$this->filter = true;
		$dataProvider = new EMongoDataProvider(Files::model()->approved(), array(
			'pagination' => array(
				'pageSize' => 5
			)
		));
		$this->render(
			'index', array(
				'data' => $dataProvider
			)
		);
	}

	/**
	 * Renders form form uploading
	 * or display dialog
	 */
	public function actionNew()
	{
		$this->render('_upload_form');
	}

	/** MODERATION */


	public function actionModerateList()
	{
		$dataProvider = new EMongoDataProvider(Files::model()->notApproved());
		$this->render(
			'moderateList', array(
				'data' => $dataProvider
			)
		);
	}

	/**
	 * Mark file as approved.
	 * Only files with full
	 * info can be approved
	 */
	public function actionApprove($id)
	{
		/* action can be preformed only by moderators */
		$file = $this->loadModel($id);
		if (!$file->approve()) {
			throw new CHttpException(418, "Model can not be saved");
		}
	}

	public function actionDeny($id)
	{
		/* action can be preformed only by moderators */
		//TODO Send message to user
		$file = $this->loadModel($id);
		if (!$file->deny()) {
			throw new CHttpException(418, "Model can not be saved");
		}
	}

	public function actionApproveChild($id)
	{
		/* action can be preformed only by moderators */
		//TODO Send message to user
		$file = $this->loadModel($id);
		if (!$file->setChild()) {
			throw new CHttpException(418, "Model can not be saved");
		}
	}

	public function actionModerate($id)
	{
		$file = $this->loadModel($id);

		if (isset($_POST['Files'])) {
			$file->setScenario('update');
			$file->attributes = $_POST['Files'];
			if ($file->validate() && $file->save()) {
				echo CJSON::encode(['success' => Yii::t('app', 'File information updated')]);
			}
		}

		$this->render(
			'moderate', array(
				'model' => $file
			)
		);
	}

	/* MODERATION END */
	/**
	 * Displays found file's data
	 *
	 * @param $q
	 *
	 */
	public function actionSearch($q)
	{
		if (empty($q) || strlen($q) < 3) {
			echo CJSON::encode(array('error' => Yii::t('app', 'The query length can not be less then 3 chars')));
			Yii::app()->end();
		}
		if (!extension_loaded("sphinx")) {
			echo CJSON::encode(
				array(
					'class_error' => Yii::t('app', 'No sphinx module is available.It must be installed and enable to use search.')
				)
			);
			Yii::app()->end();
		}
		$criteria = new ESphinxSearchCriteria(array(
			'sortMode'   => ESphinxSort::RELEVANCE,
			'matchMode'  => ESphinxMatch::PHRASE,
			'maxMatches' => 50,
			'limit'      => 10
		));

		$query = new ESphinxQuery($this->escapeString($q), 'books', $criteria); // search in all fields
		$sq_result = Yii::app()->sphinx->executeQuery($query);

		if ($sq_result->count() == 0) {
			echo CJSON::encode(array('no_results_found' => Yii::t('app', 'Try to use custom search')));
			Yii::app()->end();
		}

		for ($i = 0; $i < $sq_result->count(); $i++) {
			if ($sq_result->offsetExists($i)) {
				$item = $sq_result->offsetGet($i);
				$ids[] = new MongoInt64($item->id);
				$weights[$item->id] = $item->weight;
			}
		}
		//use code below to get data from database
		$data = db()->storage->files->find(
			array('sphinx_id' => array('$in' => $ids)),
			array(
				'title'     => 1,
				'authors'   => 1,
				'sphinx_id' => 1
			)
		)
			->limit(10);
		if (iterator_count($data) == 0) {
			echo CJSON::encode(array('no_data_to_return' => Yii::t('app', 'Try to use search in few minutes')));
			Yii::app()->end();
		}
		//this must be simplest
		foreach ($weights as $id => $weight) {
			foreach ($data as $doc_id => $document) {
				if ($id == $document['sphinx_id']) {
					$document['id'] = strval($document['_id']);
					unset($document['_id']);
					unset($document['sphinx_id']);
					$result[] = $document;
				}
			}
		}
		echo CJSON::encode($result);
	}

	public function actionRecommended()
	{
		$this->render('index', ['data' => new EMongoDataProvider(Files::model()->recently()->approved(), [
			'pagination' => false
		])]);
	}

	/**
	 * @return latest files
	 */
	public function actionHot()
	{
		$this->render('index', [
				'data' => new EMongoDataProvider(Files::model()->recently()->approved(), [
						'pagination' => false
					]
				)
			]
		);
	}

	/**
	 * Renders user's file list
	 */
	public function actionMy()
	{
		$c = new EMongoCriteria;
		$c->addCondition('user', Yii::app()->user->login);
		$c->setSort(array('uploadDate' => -1));
		$dataProvider = new EMongoDataProvider('Files', array(
			'criteria' => $c,
		));
		$this->render(
			'my', array(
				'data' => $dataProvider
			)
		);
	}

	private function vote($type)
	{
		switch ($type) {
			case 'up':
				$voteNumber = 1;
				$votePlus = 2;
				break;
			case 'down':
				$voteNumber = -1;
				$votePlus = -2;
				break;
		}
		$file = Files::model()->findByPk(new MongoId(CHttpRequest::getParam('id')));
		if ($file != null) {
			$user = Yii::app()->user->name;
			if (isset($file->votes)) {
				foreach ($file->votes as $vote) {
					if ($vote->user == $user && $vote->vote != -($voteNumber)) {
						echo CJSON::encode(array('error' => Yii::t('app', 'You can`t vote anymore')));
						Yii::app()->end();
					} elseif ($vote->user == $user) {
						$voteNumber = $votePlus;
					}
				}
			}
			$file->votes[] = new FileVote;
			end($file->votes)->user = $user;
			end($file->votes)->vote = $voteNumber;
			end($file->votes)->created = new MongoDate();
			$file->save();
			echo CJSON::encode(array('success' => Yii::t('app', 'Thank you for voting')));
		} else {
			echo CJSON::encode(array('error' => Yii::t('app', 'No such file')));
		}
		Yii::app()->end();
	}

	public function actionVoteUp()
	{
		$this->vote('up');
	}

	public function actionVoteDown()
	{
		$this->vote('down');
	}

	/**
	 * Out file stream to browser,
	 * send headers for saving file,
	 * increment download counter
	 *
	 * @param $id
	 *
	 * @throws CHttpException
	 */
	public function actionDownload($id)
	{
		$f = FileStorage::model()->findByPk(new MongoId($id));
		if (is_null($f)) {
			throw new CHttpException(404, Yii::t('app', 'Requested file does not exists.'));
		}
		if ($f->getFile()->file['status'] == Files::STATUS_NOT_APPROVED) {
			throw new CHttpException(403, Yii::t('app', 'This file has not been approved yet.'));
		}
		$stream = $f->getFile()->getResource();
		header('Content-Description: File Transfer');
		header('Content-type: ' . $f->getFile()->file['mime']);
		header('Content-Disposition: attachment; filename=' . ($f->getFile()->file['name']));
		header('Content-Transfer-Encoding: binary');
		header('Pragma: public');
		header('Content-Length: ' . $f->getFile()->getSize());
		while (!feof($stream)) {
			echo fread($stream, 8192);
		}
		Files::model()->updateByPk($f->_id, array('$inc' => array("downloads" => 1)));
	}

	/**
	 * Renders single document
	 *
	 * @param $id
	 *
	 * @throws 403 error if status not_approved
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);
		if ($model->status == Files::STATUS_NOT_APPROVED) {
			throw new CHttpException('403', Yii::t('app', 'Access denied to not approved materials'));
		}
		$this->render('view', array('model' => $model));
	}

	/**
	 * Delete single document
	 *
	 * @param $id
	 *
	 * @throws CHttpException
	 */
	public function actionDelete($id)
	{
		$model = $this->loadModel($id);
		if (!$this->_isOwner($model) || $model->status == Files::STATUS_APPROVED) {
			throw new CHttpException(403, Yii::t('app', 'You can not delete this material'));
		}
		try{
			$model->delete();
			echo CJSON::encode(['status' => 'success']);
		}
		catch(Exception $e){
			echo CJSON::encode(['status' => 'error','message'=>$e->getMessage()]);
		}
	}

	/**
	 * Handle post request,
	 * output status in json format
	 */
	public function actionUpload()
	{
		header('Content-Type: application/json');
		if ($file = CUploadedFile::getInstanceByName('file')) {
			$model = new FileStorage();
			$model->file = $file;
			if (isset($_POST['parent'])) {
				$model->parent = $_POST['parent'];
				$model->setScenario('childFile');
			} else {
				$model->setScenario('checkFile');
			}
			if ($model->validate()) {
				unset($model->file);
				$model->setScenario('insert');
				$file->saveAs($file->getTempName());
				$model->name = $file->getName();
				$model->mime = $file->getType();
				$model->setFile($file->getTempName());
				$model->addFileToQueue();
			} else {

src/protected/views/layouts/column1.php
<?php
/* @var $this Controller */
$class = 'pure-u-1';
?>
<?php $this->beginContent('//layouts/main'); ?>
<?php if ($this->filter): ?>
	<?php $this->renderPartial('//layouts/filter'); ?>
	<?php $class = "pure-u-lg-4-5 pure-u-md-3-4 pure-u-1"; ?>
<?php endif; ?>
	<div class="<?php echo $class; ?>" id="content">

		<?php echo $content; ?>

	</div>
<?php $this->endContent(); ?>

src/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

src/protected/views/layouts/filter.php
<div class="pure-u-lg-1-5 pure-u-md-1-4 pure-u-1" id="filter">
	<p>
		Item 1
	</p>

	<p>
		Item 2 and it is very long
	</p>
</div>

src/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php
		$baseUrl = Yii::app()->baseUrl;
		$cs = Yii::app()->getClientScript();

		$cs->registerCoreScript('jquery');
		$cs->registerScriptFile($baseUrl . '/js/typeahead.js');
		$cs->registerScriptFile($baseUrl . '/js/jquery.cookie.js');
		$cs->registerScriptFile($baseUrl . '/js/catalog.js');
		$cs->registerScriptFile($baseUrl . '/js/bootstrap.min.js');
	?>
	<link rel="stylesheet" href="<?php echo $baseUrl; ?>/css/styles.css">
	<link rel="stylesheet" href="<?php echo $baseUrl; ?>/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $baseUrl; ?>/css/grids-responsive-min.css">
	<link rel="shortcut icon" href="<?php echo $baseUrl; ?>/images/favicon.png" type="image/png">
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>
<body>
	<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header title pure-u-1 pure-u-sm-2-5 pure-u-md-1-3 pure-xl-1-3">
				<a href="/">
					<div class="logotype"></div>
					<div class="title-text">
						<h2>USIC</h2>
						<h1 class="green_text">catalog</h1>
					</div>
				</a>
			</div>
			<div class="right pure-u-lg-1-4 pure-u-md-1-3 pure-xl-1-3">
				<div class="social">
					<a href="http://vk.com/share.php?url=http://cat.usic.at&title=usic Catalog — каталог навчальних матеріалів"
					   title="Поділитись посиланням вконтакті"></a>
					<a href="http://www.facebook.com/sharer.php?u=http://cat.usic.at"
					   title="Поділитись посиланням на facebook"></a>
					<a href="http://twitter.com/share?url=http://cat.usic.at&text=usic Catalog — каталог навчальних матеріалів"
					   title="твітнути посилання"></a>
					<a href="http://feedback.usic.at" title="написати розробникам проекту"></a>
				</div>

			</div>
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            	<span class="sr-only">Toggle navigation</span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
          	</button>
          	<div class="navbar-collapse collapse">
            	<?php $this->widget('zii.widgets.CMenu', array(
            		'htmlOptions' => array('class' => 'nav navbar-nav'),
					'items' => array(
					array('label' => 'Все', 'url' => '/', 'active' => Yii::app()->controller->id == 'files' and Yii::app()->controller->action->id == 'index'),
					array('label' => 'Рекомендоване', 'url' => array('files/recommended'), 'visible' => !Yii::app()->user->isGuest),
					array('label' => 'Література до курсів', 'url' => array('files/courses'), 'visible' => !Yii::app()->user->isGuest),
					array('label' => 'Моє', 'url' => array('files/my'), 'visible' => !Yii::app()->user->isGuest),
					array('label' => 'Додати', 'url' => array('files/new'), 'visible' => !Yii::app()->user->isGuest),
					array('label' => 'Вхід', 'url' => array('site/login'), 'visible' => Yii::app()->user->isGuest),
					array('label' => 'Пошук', 'url' => '#', 'linkOptions'=>array('class'=>"search"), 'visible' => !Yii::app()->user->isGuest),
					),
				));?>
				<div class="slideup form-wrapper" id="wrapper">
					<form class="navbar-form navbar-right">
						<input type="text" placeholder="пошук по каталогу..." class="form-control">
						<input type="submit" value="" placeholder="Шукати!">
					</form>
				</div>
        	</div>
		</div>
	</div>
	<!--navbar-->

	<div class="content">
		<?php echo $content; ?>
	</div>
	<footer>
		<hr>
		<a href="/tou"><h3>умови використання</h3></a>
		<a href="/help"><h3>довідка</h3></a>
		<a href="http://usic.at/"><h3>Ukma Student Internet Center</h3></a>
	</footer>
</body>
</html>

src/protected/views/layouts/meta.php
<?php
/**
 * @docs http://www.w3schools.com/tags/tag_meta.asp
 */

$socials = array('social_description', 'social_images', 'social_title');
$w3c = array('application-name', 'author', 'description', 'generator', 'keywords');

$data = isset($data) ? $data : array();
$metadata = (isset(Yii::app()->params['meta']) && is_array(Yii::app()->params['meta']))
	? array_merge_recursive(Yii::app()->params['meta'], $data) : $data;

foreach ($metadata as $key => $value) {
	if (in_array($key, $w3c)) {
		Yii::app()->clientScript->registerMetaTag($value, $key);
	}
	if (in_array($key, $socials)) {
		$key = str_replace('social_', '', $key);
		if ($key == 'images') {
			$images = is_array($value) ? $value : array($value);
			foreach ($images as $image)
				Yii::app()->clientScript->registerMetaTag(Yii::app()->createAbsoluteUrl($image), null, null, array('property' => 'og:image'));
		} else {
			Yii::app()->clientScript->registerMetaTag($value, null, null, array('property' => 'og:' . $key));
		}
	}
}