src/protected/models/Comment.php
<?php


class Comment extends CFormModel{

	public $comment;
	public $file_id;

	public $user;
	public $time_created;

	private $_file;

	public function rules()
	{
		return array(
			array('comment, file_id', 'required', 'on' => 'addComment'),
			array('comment', 'length', 'max' => 500, 'on' => 'addComment'),
			array('file_id', 'match', 'pattern' => '/^[0-9a-fA-F]{24}$/', 'message' => 'Not MongoId'),
			array('file_id', 'fileApproved', 'skipOnError' => true),
			array('user', 'default', 'value' => Yii::app()->user->login, 'on' => 'addComment'),
			array('time_created', 'default', 'value' => new MongoDate(), 'on' => 'addComment'),
		);
	}

	public function fileApproved($attribute, $params)
	{
		$this->_loadFile();
		if(is_null($this->_file)){
			$this->addError('file_id', 'No such file');
		} else if(!$this->_file->approved()){
			$this->addError('file_id', 'File is not approved');
		}
	}

	public function saveComment()
	{
		$this->_file->comments[] = array('user' => $this->user, 'time_created' => $this->time_created, 'comment' => $this->comment);
		return $this->_file->save(false);
	}

	public function getFileComments()
	{
		return $this->_file->comments;
	}

	private function _loadFile()
	{
		if(!isset($this->_file)){
			$this->_file = Files::model()->findBy_id($this->file_id);
		}
	}
} 

src/protected/controllers/CommentsController.php
<?php


class CommentsController extends Controller{

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + add',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 *
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array(
				'allow',
				'actions' => array('fileComments'),
				'users'   => array('*'),
			),
			array(
				'allow',
				'actions' => array('add'),
				'users'   => array('@'),
			),
			array(
				'deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	public function actionAdd()
	{
		header('Content-Type: application/json');
		if(isset($_POST['Comment'])) {
			$comment = new Comment();
			$comment->setScenario("addComment");
			$comment->attributes = $_POST['Comment'];
			if($comment->validate()) {
				$comment->saveComment();
			} else {
				throw new CHttpException('400', CJSON::encode(array('error' => $comment->getErrors())));
			}
		}
	}

	public function actionFileComments($file_id)
	{
		$comment = new Comment();
		$comment->file_id = $file_id;
		if($comment->validate()){
			$this->renderPartial('_commentsList', array('comments' => $comment->getFileComments()));
		} else {
			throw new CHttpException('400', CJSON::encode(array('error' => $comment->getErrors())));
		}
	}
} 

src/protected/views/comments/_comments.php
<script>
	function sendComment()
	{
		$.ajax({
			url: '<?php echo $this->createUrl('comments/add') ?>',
			type: 'POST',
			data: {
					Comment: {
						file_id: '<?php echo $file; ?>',
						comment: $('#comment').val()
					}
				  },
			dataType: 'json',
			error: function(xhr, status, error){
				alert(xhr.responseText);
			}
		}).success(function(){
			$('#comment').val('');
			reloadComments();
		});
	}

	function reloadComments()
	{
		$.ajax({
			url: '<?php echo $this->createUrl('comments/fileComments') ?>',
			type: 'GET',
			data: {
				file_id: '<?php echo $file; ?>'
			},
			dataType: 'html',
			error: function(xhr, status, error){
				alert(xhr.responseText);
			}
		}).success(function($data){
			$('#comments').empty().append($data);
		});
	}

	$(document).ready(function(){
		$('#sendComment').click(function(){
			sendComment();
		});
	})
</script>

<div id="comments">
<?php $this->renderPartial('//comments/_commentsList',array(
	'comments'=>$comments
)); ?>
</div>

<?php if(!Yii::app()->user->isGuest): ?>
	<textarea rows="5" cols="50" id="comment">
	</textarea>
	<button id="sendComment">Прокоментувати</button>
<?php endif?>

src/protected/views/comments/_commentsList.php
<?php if(count($comments) == 0): ?>
	<div> Прокоментуйте першими </div>
<?php else: ?>
	<ul>
		<?php foreach($comments as $comment): ?>
			<li>
				<div><?php echo $comment['user']; ?></div>
				<div><?php echo date(' h:i:s d-M-Y', $comment['time_created']->sec); ?></div>
				<div><?php echo CHtml::encode($comment['comment']); ?></div>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>